### PR TITLE
Add AP305 support

### PR DESCRIPTION
**Pull request by rixxxx**
This will add AP305 support.

### CODE REVIEW

**Comment by NHAS** [comment]
Oh shoot I forgot to merge this, thanks for you work!

**Comment by rixxxx** [comment]
Don't know about AP350, but it works on AP305C. I'm able to get into _shell with the produced key.

**Comment by NHAS** [comment]
I just misread haha, but yeah thats fantastic thanks!

**Comment by zlinuxboy** [comment]
It did not work, I build the binary success, but when generate password, the binary emit nothing.
I have to manually delete
```
case "305":
```
to get the code work as expect.

**Comment by NHAS** [comment]
Yeah a friend of mine also found this. its because in your PR you assumed golang switch statements worked like C switch statements. 

My bad for not testing it haha

**Comment by zlinuxboy** [comment]
hi, nhas.
I have other type of aerohive device, such as 121, 330, 250, 245 etc, would like to add extra support. but have no idea to find out this info.
```
	platformSecret := [16]byte{'T', 'I', 'U', 't', '8', 'K', 'k', '5', 'A', '7', 'd', '4', 'W', 'i', 'r', 'H'}

	//"02301601202422"
	serial := []byte(str_serial)

	magic_strings_littlendian := []uint32{
		0x1cbe3df0,
		0xd034ed14,
		0x86487844,
		0x3dc2c339,
		0x427fdcb7,
		0xf06e8381,
		0xe82c9e44,
		0xeafcc130,
	}
```
 sorry, I am just a network admin rather than a coder. have little knownldeg of golang.

**Comment by rixxxx** [comment]
Sorry for writing C :)

PS: _shell command doesn't do anything(no password prompt, it just returns) on 305 with the 10.5r4 software.

**Comment by NHAS** [comment]
Yep on the newest firmware they have disabled the secret shell command.

To find the magic values you nerd to have a shell on the device itself and then you have to read some files along with decompile the shared library that is used to generate the password.

My colleague is putting out some research soon on aerohive devices. It would be my recommendation to discontinue your use of aerohive devices as soon as possible.

But I can't give any more details than that at this stage.

**Comment by rixxxx** [comment]
Interesting...

**Comment by zlinuxboy** [comment]
Any progress? I am intersting too.

**Comment by NHAS** [comment]
Not sure what you mean by any progress. They'll be releasing their work after the 90 day responsible disclosure agreement :)

**Comment by zlinuxboy** [comment]
Then, their discovery will be release after 3 months after nowaday?

**Pull request merged**
